MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/data_sata/ReID_Group/ReID_Group/KANTransfarmers/TransReID/checkpoint/kat_base_patch16_224.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('2')
  TRANSFORMER_TYPE: 'kat_base_patch16_224_TransReID'  # Change from vit to kat
  STRIDE_SIZE: [16, 16]

KAT:
  ACTIVATION: "swish" 
  WEIGHT_INIT: "kan_mimetic"

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: ('/data_sata/ReID_Group/ReID_Group/KANTransfarmers/TransReID/data')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  MAX_EPOCHS: 60
  BASE_LR: 0.002
  IMS_PER_BATCH: 192
  WARMUP_METHOD: 'linear'
  WARMUP_EPOCHS: 10
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 60
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  FREEZE_BACKBONE_EPOCHS: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: '../logs/market_kat_transreid_20'